// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY7hgNwuTi_hytxDME0grUHlNVCAtmibY',
    appId: '1:158270908028:web:5fd9b5883c79ce6ef30bf9',
    messagingSenderId: '158270908028',
    projectId: 'ar-based-tourist-guide',
    authDomain: 'ar-based-tourist-guide.firebaseapp.com',
    storageBucket: 'ar-based-tourist-guide.firebasestorage.app',
    measurementId: 'G-SMC65M6ZF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPIFkI13pUj0rt4lBoJY85vSjK4etwuA',
    appId: '1:158270908028:android:72ed43097cc9e7f3f30bf9',
    messagingSenderId: '158270908028',
    projectId: 'ar-based-tourist-guide',
    storageBucket: 'ar-based-tourist-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA5vLtfDxVDiB0Fqu7zROw6woYzetENP4',
    appId: '1:158270908028:ios:4f774b2f58661a62f30bf9',
    messagingSenderId: '158270908028',
    projectId: 'ar-based-tourist-guide',
    storageBucket: 'ar-based-tourist-guide.firebasestorage.app',
    iosBundleId: 'com.example.ethioarGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA5vLtfDxVDiB0Fqu7zROw6woYzetENP4',
    appId: '1:158270908028:ios:4f774b2f58661a62f30bf9',
    messagingSenderId: '158270908028',
    projectId: 'ar-based-tourist-guide',
    storageBucket: 'ar-based-tourist-guide.firebasestorage.app',
    iosBundleId: 'com.example.ethioarGuide',
  );
}
